### PR TITLE
Add date time to log

### PR DESCRIPTION
**Pull request by sepo274**

### CODE REVIEW

**Comment by Razikus** [comment]
Is it pointed to the headless version?

**Comment by Razikus** [comment]
Is it pointed to the headless version?

**Comment by sepo274** [comment]
> Is it pointed to the headless version?

both headless and headful, I have added date-time into log messages, just to keep consistency.

**Comment by opengs** [comment]
Code from this PR was manually added to the application, because there where a lot of changes (full refactoring)

**Pull request closed without merging**
