### PR TITLE
Changed azure custom script

### PR DESCRIPTION
**Pull request by vtinkerer**

### CODE REVIEW

**Comment by OleksandrChekmez** [comment]
If we create number of docker containers == vCPUs, we get 100% CPU load a the time. I cause account block.
Recommend to create vCPU-1 containers, see adjusted script in my fork: https://github.com/OleksandrChekmez/uashield/blob/master/tools/azure/azure-custom-data-script.sh

**Comment by vtinkerer** [comment]
My instances were working a few days on 100% CPU load. I'm still not banned.

**Comment by aot9** [comment]
what about adding similar limitation for threads count ? 7500 looks insane, my heuristic is that you should have at most 512 threads per 1Gb RAM, otherwise you will eventually hit memory issues (at least on Ubuntu 20.04, maybe it is different for Win).
Also script could be useful for deploy on any VDS provider, it is a bit confusing that it is hidden in azure specific folder.

**Comment by OleksandrChekmez** [comment]
@aot9 7500 threads works fine for me on 4 vCPU 8GB RAM, but I have 3 containers, not 4. OS - Ubuntu 20.04
This script should work fine on any linux machine.

**Pull request merged**
