### PR TITLE
Fixed markup in Azure Readme

### PR DESCRIPTION
**Pull request by vtinkerer**

### CODE REVIEW

**Comment by OleksandrChekmez** [comment]
- recommend creating 4 vCPUs. 
- Cost example is not correct, spot instances are much cheaper

Since I don`t have write rights I adjusted README.md, README-en.md and tools/azure/Readme.md in my fork:
https://github.com/OleksandrChekmez/uashield

**Comment by Razikus** [comment]
Make pull request in order to merge it if you want

**Comment by vtinkerer** [comment]
1) Why 4?
2) I calculated for the worst possible situation (max price per hour for spot instance)

**Comment by OleksandrChekmez** [comment]
1. There was a case when account was blocked, see dev thread in Discord

**Comment by denysbutenko** [comment]
1. It is default limits per region on the Azure side. My account was locked temporarily due to running 5 docker containers per VM. So, I reverted back changes to use one container with more threads instead, it works well now.

**Pull request merged**
