### PR TITLE
Added guide for Azure

### PR DESCRIPTION
**Pull request by vtinkerer**

### CODE REVIEW

**Review by Andrii-L-DDoSer — COMMENTED** [review]
good, let's merge and release new version :) Just saying :) I assume `v0.0.10` :)

**Comment by Razikus** [comment]
Please resolve conflicts
All PR into 0.0.x

**Comment by Razikus** [comment]
All text based PR's into docsimprovement, plz check conflicts

**Comment by vtinkerer** [comment]
Slamy said they don't want to add external links to Readme, so I'm waiting for creation of special page for instructions.

**Pull request closed without merging**
