### PR TITLE
Fix/doser promise all

### PR DESCRIPTION
**Pull request by PawFV**
* Має бути швидше. обіцянки виконуються паралельно.
* Відокремлена логіка від типів і констант.

----

* Should speed up, promises are done in parallel.
* Decoupled logic from types and constants.

### CODE REVIEW

**Review by rom-melnyk — APPROVED** [review]

**Comment by Razikus** [comment]
Hi! Thanks for the PR. We just apply another pull request that is conflicting with your changes. Can you check if it still applies?

**Comment by PawFV** [comment]
@Razikus Conflicts solved.

**Comment by Razikus** [comment]
Will check that tommorow, looks nice
But i'm aware of one thing - does it support proxy without password now also? (cant find ProxyData)

**Comment by PawFV** [comment]
https://github.com/PawFV/uashield/blob/140af14405fbaea46edf9f7ae813470dd9b4e057/src-worker/types.ts#L1-L5

I'm not aware of that feature mind providing some context or if I missed something can you suggest the change? thanks :)

**Review by Andrii-L-DDoSer — COMMENTED** [review]
@yastasiuk чи @Razikus відпишіть десь в Телеграм чатах про НОВУ версію `0.0.9` чи чи буде `0.0.10` і чи з новими проксі чи ОК чи ні. Заспокойте користувачів.

**Comment by Razikus** [comment]
Sure, i will just check it 
Cause we added support for proxies that have no password, and i'm not sure if you are touching this, but probably not

@Andrii-L-DDoSer i wrote to proper person about this

**Comment by PawFV** [comment]
Solved conflicts again.

**Pull request merged**
