### PR TITLE
Added custom script for Azure

### PR DESCRIPTION
**Pull request by v-baida**

### CODE REVIEW

**Comment by Razikus** [comment]
hey
Can you add this to the /tools/azure/ ?
Also provide some kind of readme how to use it

**Comment by OleksandrChekmez** [comment]
See [discussion in #67 ](https://github.com/opengs/uashield/issues/67#issuecomment-1059113547)

**Comment by OleksandrChekmez** [comment]
Noticed that VMs with 2vCPUs and 8RAM stop working normally, CPU load 100%, network usage 0. RAM 100%. I suppose [azure-custom-data-script.sh](https://github.com/opengs/uashield/blob/master/tools/azure/azure-custom-data-script.sh) should be adjusted and run amount of workers=number of vCPU.

May be instead of hardcoded 5 workers, we should get number of cores automatically:
workers_qty="grep -c ^processor /proc/cpuinfo"

**Comment by vtinkerer** [comment]
Ok, sure

**Pull request merged**
