### PR TITLE
Feat/docs - static site generator

### PR DESCRIPTION
**Pull request by PawFV**
Adds static site generator for docs with localization

### CODE REVIEW

**Comment by Razikus** [comment]
Hey, is it somehow generated? 
We need to automate it then with GH action

**Comment by PawFV** [comment]
@Razikus I wrote the instructions in discord yesterday, if you dont find them just lmk.

Yes it can be automated, if you deploy it to netlify in the example I gave you it will be automatically integrated from Netlify, no need to run github actions.

If you are not opting this methods keep in mind this things.

In /docs folder is where the nuxt docs project exists, you can run different scripts from package json. check `README.md`

Deploy purposes you will run: `yarn generate` -> will create static site in `/docs/dist`, this is the folder you need to deploy.

**Comment by Razikus** [comment]
will resolve that tommorow

**Comment by Razikus** [comment]
Decided not to merge - we should not use external services as amuch as we can not use external services

**Pull request closed without merging**
