### PR TITLE
Tray icon support and app start on startup

### PR DESCRIPTION
**Pull request by sepo274**

### CODE REVIEW

**Comment by Razikus** [comment]
Thanks for this or
Will check it soon

**Comment by Razikus** [comment]
Sorry, had to close and reopen cause i had to recreate branch

**Comment by sepo274** [comment]
**done tray icon and open at startup**

1) tray icon, can be opened with right and left mouse click, show restores (unminimize window) and set focus 
Screenshot 2022-03-08 at 12 36 57

 2) open at startup, sets app into register (win and mac)
Screenshot 2022-03-08 at 12 37 57

overall adv setting menu: 
Screenshot 2022-03-08 at 12 37 47

the dirty hack is used to prevent minimize in dev mode (app reload on code change)
```
if (process.env.DEBUGGING) {
    // if on DEV or Production with debug enabled
    mainWindow.webContents.openDevTools()
    // close window on reload
    isQuite = true
```

**Comment by opengs** [comment]
Sorry for very long response. Will merge this in new version :)

**Pull request merged**
